name = "cf-notepad"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV 命名空间配置
# 请将此文件复制为 wrangler.toml 并填入您的实际 KV 命名空间 ID
[[kv_namespaces]]
binding = "NOTEPAD_KV"
id = "your-kv-namespace-id-here"
preview_id = "your-preview-kv-namespace-id-here"

# 管理员密码配置说明：
# 生产环境必须使用 secrets 设置密码：
#   wrangler secret put ADMIN_PASSWORD
#
# 开发环境可以在这里临时设置（不要提交到版本控制）：
# [vars]
# ADMIN_PASSWORD = "your-secure-password-here"
