name = "cf-notepad"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV 命名空间配置
# 请将此文件复制为 wrangler.toml 并填入您的实际 KV 命名空间 ID
[[kv_namespaces]]
binding = "NOTEPAD_KV"
id = "your-kv-namespace-id-here"
preview_id = "your-preview-kv-namespace-id-here"

# 环境变量（可选）
[vars]
ENVIRONMENT = "production"
